sudo: required
dist: bionic
language: minimal

matrix:
  include:
    # command line only images
    - env: ARCH=armhf VARIANT=minimal RECIPE=halium
    - env: ARCH=arm64 VARIANT=minimal RECIPE=halium
    - env: ARCH=i386 VARIANT=minimal RECIPE=halium
    - env: ARCH=armhf VARIANT=minimal RECIPE=mainline
    - env: ARCH=arm64 VARIANT=minimal RECIPE=mainline
    - env: ARCH=i386 VARIANT=minimal RECIPE=mainline
    - env: ARCH=arm64 VARIANT=minimal RECIPE=anakin
    # Plasma Mobile images
    - env: ARCH=armhf VARIANT=plasma-mobile RECIPE=halium
    - env: ARCH=arm64 VARIANT=plasma-mobile RECIPE=halium
    - env: ARCH=i386 VARIANT=plasma-mobile RECIPE=halium
    - env: ARCH=armhf VARIANT=plasma-mobile RECIPE=mainline
    - env: ARCH=arm64 VARIANT=plasma-mobile RECIPE=mainline
    - env: ARCH=i386 VARIANT=plasma-mobile RECIPE=mainline
    - env: ARCH=arm64 VARIANT=plasma-mobile RECIPE=anakin

before_install:
  # Reset sources list (travis default ppas are often broken)
  - echo "deb http://us.archive.ubuntu.com/ubuntu/ bionic main universe" |sudo tee /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install dpkg debian-archive-keyring -y
  - echo "deb http://deb.debian.org/debian testing main" |sudo tee -a /etc/apt/sources.list
  - sudo apt-get update

install:
  - sudo apt-get install debos bmap-tools dosfstools e2fsprogs zsync -y

script:
  - sudo debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml

deploy:
  provider: script
  skip_cleanup: true
  script: ./rsync_deploy.sh
  on:
    branch: master
