sudo: required
dist: xenial

matrix:
  include:
    # command line only images
    - env: ARCH=armhf VARIANT=default RECIPE=halium
    - env: ARCH=arm64 VARIANT=default RECIPE=halium
    - env: ARCH=i386 VARIANT=default RECIPE=halium
    - env: ARCH=armhf VARIANT=default RECIPE=mainline
    - env: ARCH=arm64 VARIANT=default RECIPE=mainline
    - env: ARCH=i386 VARIANT=default RECIPE=mainline
    # Plasma Mobile images
    - env: ARCH=armhf VARIANT=plamo RECIPE=halium
    - env: ARCH=arm64 VARIANT=plamo RECIPE=halium
    - env: ARCH=i386 VARIANT=plamo RECIPE=halium
    - env: ARCH=armhf VARIANT=plamo RECIPE=mainline
    - env: ARCH=arm64 VARIANT=plamo RECIPE=mainline
    - env: ARCH=i386 VARIANT=plamo RECIPE=mainline

before_install:
  - sudo apt-get update
  - sudo apt-get install dpkg debian-archive-keyring -y
  - echo "deb http://deb.debian.org/debian testing main" |sudo tee -a /etc/apt/sources.list
  - sudo apt-get update

install:
  - sudo apt-get install debos bmap-tools dosfstools e2fsprogs -y

script:
  - sudo debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml

deploy:
  provider: script
  skip_cleanup: true
  script: ./rsync_deploy.sh
  on:
    branch: master
