os: linux
dist: focal
language: shell

jobs:
  include:
    # command line only images
    - env: ARCH=armhf VARIANT=minimal RECIPE=halium
    - env: ARCH=arm64 VARIANT=minimal RECIPE=halium
    # Plasma Mobile images
    - env: ARCH=armhf VARIANT=plasma-mobile RECIPE=halium
    - env: ARCH=arm64 VARIANT=plasma-mobile RECIPE=pinephone
#    - env: ARCH=arm64 VARIANT=plasma-mobile RECIPE=librem5
    - env: ARCH=i386 VARIANT=plasma-mobile RECIPE=dell_bb

before_install:
  # Reset sources list (travis default ppas are often broken)
  - sudo rm /etc/apt/sources.list.d/ -rf && sudo dpkg --remove-architecture i386
  - echo "deb http://us.archive.ubuntu.com/ubuntu/ focal main universe" | sudo tee /etc/apt/sources.list
  - sudo apt-get update && sudo apt-get install dpkg debian-archive-keyring -y
  - sudo cp /usr/share/keyrings/debian-archive-keyring.gpg /etc/apt/trusted.gpg.d/debian-archive-keyring.gpg
  - echo "deb http://deb.debian.org/debian testing main" |sudo tee -a /etc/apt/sources.list
  - sudo apt-get update

install:
  - sudo apt-get install debos bmap-tools dosfstools e2fsprogs zsync -y

script:
  - sudo ./bin/debos -t variant:${VARIANT} -t architecture:${ARCH} ${RECIPE}.yml

deploy:
  provider: script
  skip_cleanup: true
  script: ./rsync_deploy.sh
  on:
    branch: master
